### ISSUE TITLE
'low' or 'full' profile

### ISSUE THREAD

**Issue by SwaggyZhang** [tdopierre/ProtAugment#4]
Hello, thanks for your valuable work.
I have some confusions about the results of experiments in Table 4 of your paper. Could you please explain the details of 'given only 10 labeled samples per class **(low profile)**' to me?

**Comment by tdopierre** [comment]
Hi, 
In the **low profile**, training classes are limited to 10 samples each. That means that when drawing a training episode, the K shots taken from each class of the episode are taken among 10 fixed samples (those 10 samples are fixed for the whole run).
In practice, it means using the training file **train.10samples.jsonl** instead of **train.jsonl**
For example, in the directory [data/BANKING77/few_shot/01](https://github.com/tdopierre/ProtAugment/tree/main/data/BANKING77/few_shot/01) (corresponding to the `BANKING77` dataset, 1st cross-validation split):
- There are 25 training classes (`labels.train.txt` contains 25 lines)
- The **full** training file `train.jsonl` contains 4336 samples
- The **low** training file `train.10samples.jsonl` contains 250 samples (10 for each of the 25 classes)

The overall goal of running this **low** profile is to simulate some extreme conditions where there is a very limited amount of training samples.

**Comment by SwaggyZhang** [comment]
> 

Thank you for your detailed explanation, I got it.
I wish you more excellent results.
